[package]
name = "hina-lc"
version.workspace = true
edition.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hina-core = { path = "../hina-core" }
colored = "2.0.4"
